// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Blocking
{
public static class GPGSIds
{
        public const string achievement_not_continue_5_times = "CgkIh56u3vYVEAIQBg"; // <GPGSID>
        public const string leaderboard_blocking_high_score = "CgkIh56u3vYVEAIQAQ"; // <GPGSID>
        public const string achievement_score_of_30 = "CgkIh56u3vYVEAIQBQ"; // <GPGSID>
        public const string achievement_play_20_times = "CgkIh56u3vYVEAIQAg"; // <GPGSID>
        public const string package_name = "es.victormartinezsimon.blocking"; // <GPGSID>
        public const string achievement_score_of_10 = "CgkIh56u3vYVEAIQBA"; // <GPGSID>
        public const string achievement_continue_game_10_times = "CgkIh56u3vYVEAIQAw"; // <GPGSID>

}
}
